//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Analysis2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartItem()
        {
            this.OrderCart = new HashSet<OrderCart>();
        }
    
        public int Id { get; set; }
        public int ItemID { get; set; }
        public int CartID { get; set; }
        public int ItemQuantity { get; set; }
        public bool Active { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCart> OrderCart { get; set; }
    }
}
